name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          echo "APPL????" > Info.plist
          mkdir -p Payload/GateOpener.app
          cp Info.plist Payload/GateOpener.app/
          cd Payload && zip -r app.ipa *
      - uses: actions/upload-artifact@v4
        with:
          name: app.ipa
          path: app.ipa
